packaging_format = 2

id = "taskboard"
name = "TaskBoard"
description.en = "Kanban for keeping track of things that need to get done"
description.fr = "Kanban pour garder une trace des choses à faire"

version = "v1.0.2~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "http://taskboard.matthewross.me/"
demo = "https://taskboard.matthewross.me/demo"
code = "https://github.com/kiswa/TaskBoard"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/taskboard"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/kiswa/TaskBoard/archive/refs/tags/v1.0.2.tar.gz"
        sha256 = "5ce5dc74a7333098dd3b1364104e5465443efb99392e6c5211fe0a8c226304cf"
        in_subdir = false
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "php8.2-sqlite3"
